# Generated by Django 6.0.3 on 2026-09-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('exotic', 'Exotic')], max_length=16)),
                ('discipline', models.CharField(help_text="Clinical discipline, e.g. 'Emergency & Critical Care'.", max_length=120)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=16)),
                ('body_system', models.CharField(max_length=120)),
                ('presentation', models.TextField(help_text='The signalment and presenting complaint, shown on the card.')),
                ('completion_bonus', models.PositiveIntegerField(default=25, help_text='Awarded once, when every stage of the case is correct.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='academy.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('history', 'History & signalment'), ('diagnostics', 'Diagnostic plan'), ('differential', 'Differential ranking'), ('diagnosis', 'Final diagnosis')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('briefing', models.TextField(blank=True, help_text='Clinical detail released at this stage — vitals, lab values, imaging notes. Shown above the question.')),
                ('prompt', models.CharField(max_length=300)),
                ('select_mode', models.CharField(choices=[('single', 'One answer'), ('multi', 'Several answers')], default='single', max_length=8)),
                ('points', models.PositiveIntegerField(default=10)),
                ('explanation', models.TextField(help_text='The teaching point, shown once the stage is answered.')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='academy.case')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('label', models.CharField(max_length=240)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='academy.casestage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StageAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('revealed', models.BooleanField(default=False, help_text='The model answer was shown after repeated wrong attempts. The stage unlocks the next one but earns nothing.')),
                ('tries', models.PositiveSmallIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_attempts', to='academy.caseattempt')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='academy.casestage')),
            ],
            options={
                'ordering': ['stage__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='caseattempt',
            constraint=models.UniqueConstraint(fields=('user', 'case'), name='academy_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='casestage',
            constraint=models.UniqueConstraint(fields=('case', 'order'), name='academy_stage_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='stageattempt',
            constraint=models.UniqueConstraint(fields=('attempt', 'stage'), name='academy_stage_attempt_unique'),
        ),
    ]
