# Generated by Django 6.0.3 on 2026-09-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='species',
            field=models.CharField(choices=[('canine', 'Canine (dog)'), ('feline', 'Feline (cat)'), ('lapine', 'Lapine (rabbit)'), ('musteline', 'Musteline (ferret)'), ('caviine', 'Caviine (guinea pig)'), ('murine', 'Murine (rat, mouse)'), ('rodent', 'Rodent (hamster, gerbil, chinchilla)'), ('equine', 'Equine (horse)'), ('asinine', 'Asinine (donkey, mule)'), ('bovine', 'Bovine (cattle)'), ('ovine', 'Ovine (sheep)'), ('caprine', 'Caprine (goat)'), ('porcine', 'Porcine (pig)'), ('camelid', 'Camelid (llama, alpaca)'), ('cervine', 'Cervine (deer)'), ('avian', 'Avian (bird, unspecified)'), ('psittacine', 'Psittacine (parrot, budgie, cockatiel)'), ('passerine', 'Passerine (canary, finch)'), ('galliform', 'Galliform (chicken, turkey)'), ('anseriform', 'Anseriform (duck, goose)'), ('columbine', 'Columbine (pigeon, dove)'), ('raptor', 'Raptor (hawk, falcon, owl)'), ('reptilian', 'Reptilian (reptile, unspecified)'), ('chelonian', 'Chelonian (tortoise, turtle)'), ('ophidian', 'Ophidian (snake)'), ('saurian', 'Saurian (lizard, gecko)'), ('crocodilian', 'Crocodilian (crocodile, alligator)'), ('amphibian', 'Amphibian (frog, salamander, axolotl)'), ('piscine', 'Piscine (fish)'), ('cetacean', 'Cetacean (whale, dolphin)'), ('pinniped', 'Pinniped (seal, sea lion)'), ('primate', 'Primate (non-human)'), ('marsupial', 'Marsupial (kangaroo, wombat, possum)'), ('apian', 'Apian (honeybee)'), ('wildlife', 'Wildlife (unspecified)'), ('exotic', 'Exotic (unspecified)')], max_length=16),
        ),
    ]
