/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NearbyVetsIndexRouteImport } from './routes/nearby-vets/index'
import { Route as MedicalLogIndexRouteImport } from './routes/medical-log/index'
import { Route as LifecycleIndexRouteImport } from './routes/lifecycle/index'
import { Route as ClassifyIndexRouteImport } from './routes/classify/index'
import { Route as ClassifyBreedIndexRouteImport } from './routes/classify-breed/index'
import { Route as CbcAnalyzerIndexRouteImport } from './routes/cbc-analyzer/index'
import { Route as MedicalLogRecordIdRouteImport } from './routes/medical-log/$recordId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AnimalsSlugIndexRouteImport } from './routes/animals/$slug/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyVetsIndexRoute = NearbyVetsIndexRouteImport.update({
  id: '/nearby-vets/',
  path: '/nearby-vets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalLogIndexRoute = MedicalLogIndexRouteImport.update({
  id: '/medical-log/',
  path: '/medical-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleIndexRoute = LifecycleIndexRouteImport.update({
  id: '/lifecycle/',
  path: '/lifecycle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyIndexRoute = ClassifyIndexRouteImport.update({
  id: '/classify/',
  path: '/classify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyBreedIndexRoute = ClassifyBreedIndexRouteImport.update({
  id: '/classify-breed/',
  path: '/classify-breed/',
  getParentRoute: () => rootRouteImport,
} as any)
const CbcAnalyzerIndexRoute = CbcAnalyzerIndexRouteImport.update({
  id: '/cbc-analyzer/',
  path: '/cbc-analyzer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalLogRecordIdRoute = MedicalLogRecordIdRouteImport.update({
  id: '/medical-log/$recordId',
  path: '/medical-log/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsSlugIndexRoute = AnimalsSlugIndexRouteImport.update({
  id: '/animals/$slug/',
  path: '/animals/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/medical-log/$recordId': typeof MedicalLogRecordIdRoute
  '/cbc-analyzer/': typeof CbcAnalyzerIndexRoute
  '/classify-breed/': typeof ClassifyBreedIndexRoute
  '/classify/': typeof ClassifyIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
  '/medical-log/': typeof MedicalLogIndexRoute
  '/nearby-vets/': typeof NearbyVetsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/animals/$slug/': typeof AnimalsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/medical-log/$recordId': typeof MedicalLogRecordIdRoute
  '/cbc-analyzer': typeof CbcAnalyzerIndexRoute
  '/classify-breed': typeof ClassifyBreedIndexRoute
  '/classify': typeof ClassifyIndexRoute
  '/lifecycle': typeof LifecycleIndexRoute
  '/medical-log': typeof MedicalLogIndexRoute
  '/nearby-vets': typeof NearbyVetsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/animals/$slug': typeof AnimalsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/medical-log/$recordId': typeof MedicalLogRecordIdRoute
  '/cbc-analyzer/': typeof CbcAnalyzerIndexRoute
  '/classify-breed/': typeof ClassifyBreedIndexRoute
  '/classify/': typeof ClassifyIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
  '/medical-log/': typeof MedicalLogIndexRoute
  '/nearby-vets/': typeof NearbyVetsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/animals/$slug/': typeof AnimalsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth/callback'
    | '/medical-log/$recordId'
    | '/cbc-analyzer/'
    | '/classify-breed/'
    | '/classify/'
    | '/lifecycle/'
    | '/medical-log/'
    | '/nearby-vets/'
    | '/auth/google/callback'
    | '/animals/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth/callback'
    | '/medical-log/$recordId'
    | '/cbc-analyzer'
    | '/classify-breed'
    | '/classify'
    | '/lifecycle'
    | '/medical-log'
    | '/nearby-vets'
    | '/auth/google/callback'
    | '/animals/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/auth/callback'
    | '/medical-log/$recordId'
    | '/cbc-analyzer/'
    | '/classify-breed/'
    | '/classify/'
    | '/lifecycle/'
    | '/medical-log/'
    | '/nearby-vets/'
    | '/auth/google/callback'
    | '/animals/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MedicalLogRecordIdRoute: typeof MedicalLogRecordIdRoute
  CbcAnalyzerIndexRoute: typeof CbcAnalyzerIndexRoute
  ClassifyBreedIndexRoute: typeof ClassifyBreedIndexRoute
  ClassifyIndexRoute: typeof ClassifyIndexRoute
  LifecycleIndexRoute: typeof LifecycleIndexRoute
  MedicalLogIndexRoute: typeof MedicalLogIndexRoute
  NearbyVetsIndexRoute: typeof NearbyVetsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AnimalsSlugIndexRoute: typeof AnimalsSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby-vets/': {
      id: '/nearby-vets/'
      path: '/nearby-vets'
      fullPath: '/nearby-vets/'
      preLoaderRoute: typeof NearbyVetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-log/': {
      id: '/medical-log/'
      path: '/medical-log'
      fullPath: '/medical-log/'
      preLoaderRoute: typeof MedicalLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/': {
      id: '/lifecycle/'
      path: '/lifecycle'
      fullPath: '/lifecycle/'
      preLoaderRoute: typeof LifecycleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/': {
      id: '/classify/'
      path: '/classify'
      fullPath: '/classify/'
      preLoaderRoute: typeof ClassifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify-breed/': {
      id: '/classify-breed/'
      path: '/classify-breed'
      fullPath: '/classify-breed/'
      preLoaderRoute: typeof ClassifyBreedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbc-analyzer/': {
      id: '/cbc-analyzer/'
      path: '/cbc-analyzer'
      fullPath: '/cbc-analyzer/'
      preLoaderRoute: typeof CbcAnalyzerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-log/$recordId': {
      id: '/medical-log/$recordId'
      path: '/medical-log/$recordId'
      fullPath: '/medical-log/$recordId'
      preLoaderRoute: typeof MedicalLogRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals/$slug/': {
      id: '/animals/$slug/'
      path: '/animals/$slug'
      fullPath: '/animals/$slug/'
      preLoaderRoute: typeof AnimalsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MedicalLogRecordIdRoute: MedicalLogRecordIdRoute,
  CbcAnalyzerIndexRoute: CbcAnalyzerIndexRoute,
  ClassifyBreedIndexRoute: ClassifyBreedIndexRoute,
  ClassifyIndexRoute: ClassifyIndexRoute,
  LifecycleIndexRoute: LifecycleIndexRoute,
  MedicalLogIndexRoute: MedicalLogIndexRoute,
  NearbyVetsIndexRoute: NearbyVetsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AnimalsSlugIndexRoute: AnimalsSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
