/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LifecycleIndexRouteImport } from './routes/lifecycle/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ClassifyIndexRouteImport } from './routes/classify/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifecycleIndexRoute = LifecycleIndexRouteImport.update({
  id: '/lifecycle/',
  path: '/lifecycle/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifyIndexRoute = ClassifyIndexRouteImport.update({
  id: '/classify/',
  path: '/classify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classify/': typeof ClassifyIndexRoute
  '/home/': typeof HomeIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classify': typeof ClassifyIndexRoute
  '/home': typeof HomeIndexRoute
  '/lifecycle': typeof LifecycleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/classify/': typeof ClassifyIndexRoute
  '/home/': typeof HomeIndexRoute
  '/lifecycle/': typeof LifecycleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/callback' | '/classify/' | '/home/' | '/lifecycle/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/callback' | '/classify' | '/home' | '/lifecycle'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/classify/'
    | '/home/'
    | '/lifecycle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClassifyIndexRoute: typeof ClassifyIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LifecycleIndexRoute: typeof LifecycleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifecycle/': {
      id: '/lifecycle/'
      path: '/lifecycle'
      fullPath: '/lifecycle/'
      preLoaderRoute: typeof LifecycleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classify/': {
      id: '/classify/'
      path: '/classify'
      fullPath: '/classify/'
      preLoaderRoute: typeof ClassifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClassifyIndexRoute: ClassifyIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LifecycleIndexRoute: LifecycleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
