# Generated by Django 6.0.3 on 2026-04-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_dss', '0002_remove_display_columns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classificationthrottlemeta',
            new_name='classify_ds_scope_40e76e_idx',
            old_name='classify_d_scope_i_8f45f6_idx',
        ),
    ]
