# Generated by Django 6.0.3 on 2026-10-03 05:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_dss', '0003_rename_classify_d_scope_i_8f45f6_idx_classify_ds_scope_40e76e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=16)),
                ('had_image', models.BooleanField(default=False)),
                ('had_notes', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('outcome', models.CharField(choices=[('diagnostic', 'Diagnosis given'), ('healthy', 'Judged healthy'), ('not_animal', 'No animal in the photo')], max_length=16)),
                ('animal_type', models.CharField(blank=True, max_length=60)),
                ('diagnosis', models.CharField(blank=True, max_length=240)),
                ('confidence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('correct', 'Correct'), ('partly', 'Partly correct'), ('incorrect', 'Incorrect'), ('unsure', 'Not sure yet')], max_length=16)),
                ('actual_diagnosis', models.CharField(blank=True, max_length=240)),
                ('confirmed_by', models.CharField(blank=True, choices=[('vet_exam', 'Vet examination'), ('lab_test', 'Lab test'), ('instructor', 'Instructor'), ('own_judgement', 'Own judgement')], max_length=16)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('shared_image_url', models.URLField(blank=True, max_length=500)),
                ('shared_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verdict'], name='classify_ds_verdict_08dbde_idx'), models.Index(fields=['diagnosis'], name='classify_ds_diagnos_08e890_idx')],
            },
        ),
    ]
