# Generated by Django 6.0.3 on 2026-10-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classify_dss', '0004_classification_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrecord',
            name='kind',
            field=models.CharField(choices=[('disease', 'Disease classification'), ('breed', 'Breed identification')], default='disease', max_length=16),
        ),
        migrations.AlterField(
            model_name='classificationrecord',
            name='confirmed_by',
            field=models.CharField(blank=True, choices=[('vet_exam', 'Vet examination'), ('lab_test', 'Lab test'), ('instructor', 'Instructor'), ('own_judgement', 'Own judgement'), ('papers', 'Pedigree papers or DNA test'), ('records', 'Breeder or shelter records')], max_length=16),
        ),
        migrations.AlterField(
            model_name='classificationrecord',
            name='outcome',
            field=models.CharField(choices=[('diagnostic', 'Answer given'), ('healthy', 'Judged healthy'), ('not_animal', 'No animal in the photo'), ('not_identified', 'Could not identify')], max_length=16),
        ),
        migrations.CreateModel(
            name='FeedbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='classify_dss.classificationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_at'],
                'indexes': [models.Index(fields=['user', 'remind_at'], name='classify_ds_user_id_f404c4_idx')],
            },
        ),
    ]
