version: "3"
services:
  app:
    image: pawmed-ai-v2.0-server
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "2002:2002" # Expose the NestJS app port to the host
    env_file:
      - .env
    networks:
      - ngrok-net

  ngrok:
    image: ngrok/ngrok:latest # Use the official ngrok image
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} # Pass your ngrok authtoken
    command: http app:2002 # Start ngrok and tunnel the app service
    ports:
      - "4040:4040" # Expose ngrok's web interface
    networks:
      - ngrok-net

networks:
  ngrok-net:
    driver: bridge
