# Generated by Django 6.0.3 on 2026-08-22 08:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('other', 'Other')], max_length=16)),
                ('species_label', models.CharField(blank=True, max_length=60)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('age_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('neuter_status', models.CharField(choices=[('intact', 'Intact'), ('neutered', 'Neutered'), ('spayed', 'Spayed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('pet_name', models.CharField(blank=True, max_length=120)),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('other', 'Other')], max_length=16)),
                ('species_label', models.CharField(blank=True, max_length=60)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('age_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('neuter_status', models.CharField(choices=[('intact', 'Intact'), ('neutered', 'Neutered'), ('spayed', 'Spayed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('test_type', models.CharField(default='cbc_panel', max_length=32)),
                ('test_date', models.DateField(default=django.utils.timezone.localdate)),
                ('values', models.JSONField(default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('result_status', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('high', 'High'), ('abnormal', 'Abnormal')], default='normal', max_length=16)),
                ('flag_count', models.PositiveSmallIntegerField(default=0)),
                ('key_findings', models.CharField(blank=True, max_length=255)),
                ('diagnostic_brief', models.TextField(blank=True)),
                ('sample_quality', models.JSONField(blank=True, default=list)),
                ('smear_morphology', models.TextField(blank=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('vet_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbc_medical_logs', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_logs', to='cbc_analyzer.pet')),
            ],
            options={
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['user', 'name'], name='cbc_analyze_user_id_4907fe_idx'),
        ),
        migrations.AddIndex(
            model_name='medicallog',
            index=models.Index(fields=['user', '-test_date'], name='cbc_analyze_user_id_c1beb1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicallog',
            index=models.Index(fields=['user', 'result_status'], name='cbc_analyze_user_id_de0fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicallog',
            index=models.Index(fields=['pet', '-test_date'], name='cbc_analyze_pet_id_8ba119_idx'),
        ),
    ]
