# Generated by Django 6.0.3 on 2026-08-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicallog',
            name='species',
            field=models.CharField(choices=[('canine', 'Canine (dog)'), ('feline', 'Feline (cat)'), ('equine', 'Equine (horse)'), ('bovine', 'Bovine (cattle)'), ('ovine', 'Ovine (sheep)'), ('caprine', 'Caprine (goat)'), ('porcine', 'Porcine (pig)'), ('rabbit', 'Rabbit'), ('ferret', 'Ferret'), ('guinea_pig', 'Guinea pig'), ('rat', 'Rat'), ('mouse', 'Mouse'), ('avian', 'Avian (psittacine)'), ('other', 'Other species')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('canine', 'Canine (dog)'), ('feline', 'Feline (cat)'), ('equine', 'Equine (horse)'), ('bovine', 'Bovine (cattle)'), ('ovine', 'Ovine (sheep)'), ('caprine', 'Caprine (goat)'), ('porcine', 'Porcine (pig)'), ('rabbit', 'Rabbit'), ('ferret', 'Ferret'), ('guinea_pig', 'Guinea pig'), ('rat', 'Rat'), ('mouse', 'Mouse'), ('avian', 'Avian (psittacine)'), ('other', 'Other species')], max_length=16),
        ),
    ]
