# Generated by Django 6.0.3 on 2026-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbc_analyzer', '0002_alter_medicallog_species_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicallog',
            name='species',
            field=models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('bovine', 'Bovine'), ('ovine', 'Ovine'), ('caprine', 'Caprine'), ('porcine', 'Porcine'), ('rabbit', 'Rabbit'), ('ferret', 'Ferret'), ('guinea_pig', 'Guinea pig'), ('rat', 'Rat'), ('mouse', 'Mouse'), ('avian', 'Avian'), ('other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('bovine', 'Bovine'), ('ovine', 'Ovine'), ('caprine', 'Caprine'), ('porcine', 'Porcine'), ('rabbit', 'Rabbit'), ('ferret', 'Ferret'), ('guinea_pig', 'Guinea pig'), ('rat', 'Rat'), ('mouse', 'Mouse'), ('avian', 'Avian'), ('other', 'Other')], max_length=16),
        ),
    ]
